# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view_car_info.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 337)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 561, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.carBrandTable = QtWidgets.QTableWidget(self.tab)
        self.carBrandTable.setEnabled(True)
        self.carBrandTable.setGeometry(QtCore.QRect(0, 0, 551, 241))
        self.carBrandTable.setObjectName("carBrandTable")
        self.carBrandTable.setColumnCount(0)
        self.carBrandTable.setRowCount(0)
        self.addBrandBtn = QtWidgets.QPushButton(self.tab)
        self.addBrandBtn.setGeometry(QtCore.QRect(10, 250, 93, 28))
        self.addBrandBtn.setObjectName("addBrandBtn")
        self.updBrandBtn = QtWidgets.QPushButton(self.tab)
        self.updBrandBtn.setGeometry(QtCore.QRect(110, 250, 93, 28))
        self.updBrandBtn.setObjectName("updBrandBtn")
        self.delBrandBtn = QtWidgets.QPushButton(self.tab)
        self.delBrandBtn.setGeometry(QtCore.QRect(210, 250, 93, 28))
        self.delBrandBtn.setObjectName("delBrandBtn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.carModelTable = QtWidgets.QTableWidget(self.tab_4)
        self.carModelTable.setGeometry(QtCore.QRect(0, 0, 551, 241))
        self.carModelTable.setObjectName("carModelTable")
        self.carModelTable.setColumnCount(0)
        self.carModelTable.setRowCount(0)
        self.delModelBtn = QtWidgets.QPushButton(self.tab_4)
        self.delModelBtn.setGeometry(QtCore.QRect(210, 250, 93, 28))
        self.delModelBtn.setObjectName("delModelBtn")
        self.updModelBtn = QtWidgets.QPushButton(self.tab_4)
        self.updModelBtn.setGeometry(QtCore.QRect(110, 250, 93, 28))
        self.updModelBtn.setObjectName("updModelBtn")
        self.addModelBtn = QtWidgets.QPushButton(self.tab_4)
        self.addModelBtn.setGeometry(QtCore.QRect(10, 250, 93, 28))
        self.addModelBtn.setObjectName("addModelBtn")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.carTypeTable = QtWidgets.QTableWidget(self.tab_2)
        self.carTypeTable.setGeometry(QtCore.QRect(0, 0, 551, 241))
        self.carTypeTable.setObjectName("carTypeTable")
        self.carTypeTable.setColumnCount(0)
        self.carTypeTable.setRowCount(0)
        self.updTypeBtn = QtWidgets.QPushButton(self.tab_2)
        self.updTypeBtn.setGeometry(QtCore.QRect(110, 250, 93, 28))
        self.updTypeBtn.setObjectName("updTypeBtn")
        self.addTypeBtn = QtWidgets.QPushButton(self.tab_2)
        self.addTypeBtn.setGeometry(QtCore.QRect(10, 250, 93, 28))
        self.addTypeBtn.setObjectName("addTypeBtn")
        self.delTypeBtn = QtWidgets.QPushButton(self.tab_2)
        self.delTypeBtn.setGeometry(QtCore.QRect(210, 250, 93, 28))
        self.delTypeBtn.setObjectName("delTypeBtn")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.carColorTable = QtWidgets.QTableWidget(self.tab_3)
        self.carColorTable.setGeometry(QtCore.QRect(0, 0, 561, 241))
        self.carColorTable.setObjectName("carColorTable")
        self.carColorTable.setColumnCount(0)
        self.carColorTable.setRowCount(0)
        self.delColorBtn = QtWidgets.QPushButton(self.tab_3)
        self.delColorBtn.setGeometry(QtCore.QRect(210, 250, 93, 28))
        self.delColorBtn.setObjectName("delColorBtn")
        self.updColorBtn = QtWidgets.QPushButton(self.tab_3)
        self.updColorBtn.setGeometry(QtCore.QRect(110, 250, 93, 28))
        self.updColorBtn.setObjectName("updColorBtn")
        self.addColorBtn = QtWidgets.QPushButton(self.tab_3)
        self.addColorBtn.setGeometry(QtCore.QRect(10, 250, 93, 28))
        self.addColorBtn.setObjectName("addColorBtn")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 563, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action_11 = QtWidgets.QAction(MainWindow)
        self.action_11.setObjectName("action_11")
        self.action_12 = QtWidgets.QAction(MainWindow)
        self.action_12.setObjectName("action_12")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.menu.addAction(self.action_11)
        self.menu.addAction(self.action_12)
        self.menu.addAction(self.action_13)
        self.menu_2.addAction(self.action_8)
        self.menu_2.addAction(self.action_9)
        self.menu_2.addAction(self.action_10)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.action_2)
        self.menu_3.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Справочники ТС"))
        self.addBrandBtn.setText(_translate("MainWindow", "Добавить"))
        self.updBrandBtn.setText(_translate("MainWindow", "Изменить"))
        self.delBrandBtn.setText(_translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Марки ТС"))
        self.delModelBtn.setText(_translate("MainWindow", "Удалить"))
        self.updModelBtn.setText(_translate("MainWindow", "Изменить"))
        self.addModelBtn.setText(_translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Модели ТС"))
        self.updTypeBtn.setText(_translate("MainWindow", "Изменить"))
        self.addTypeBtn.setText(_translate("MainWindow", "Добавить"))
        self.delTypeBtn.setText(_translate("MainWindow", "Удалить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Типы ТС"))
        self.delColorBtn.setText(_translate("MainWindow", "Удалить"))
        self.updColorBtn.setText(_translate("MainWindow", "Изменить"))
        self.addColorBtn.setText(_translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Цвета"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.menu_2.setTitle(_translate("MainWindow", "Просмотр данных"))
        self.menu_3.setTitle(_translate("MainWindow", "Помощь"))
        self.action_2.setText(_translate("MainWindow", "Справка"))
        self.action_3.setText(_translate("MainWindow", "О программе"))
        self.action_5.setText(_translate("MainWindow", "О ТС"))
        self.action_8.setText(_translate("MainWindow", "Справочники ТС"))
        self.action_9.setText(_translate("MainWindow", "О владельцах"))
        self.action_10.setText(_translate("MainWindow", "О событиях"))
        self.action_11.setText(_translate("MainWindow", "К режиму наблюдения"))
        self.action_12.setText(_translate("MainWindow", "Настройки"))
        self.action_13.setText(_translate("MainWindow", "Выход"))


